# Generated by Django 3.0.14 on 2021-12-06 12:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0008_auto_20211206_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_no',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
