# Generated by Django 3.0.14 on 2021-12-07 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_auto_20211207_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='verificationstatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=50, null=True, verbose_name='Approval status')),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='verification_status',
        ),
        migrations.AddField(
            model_name='invoice',
            name='qmsstatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invoice.verificationstatus', verbose_name='Verification Status:'),
        ),
    ]
